services:
  db:
    image: postgres:15-alpine
    container_name: nestjs-template-compose-db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    networks:
      - default

  backend:
    build: .
    container_name: nestjs-template-backend
    ports:
      - "4242:4242"
    depends_on:
      - db
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@nestjs-template-compose-db:5432/${PGDATABASE}?schema=public&connect_timeout=300
      - DIRECT_DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@nestjs-template-compose-db:5432/${PGDATABASE}?schema=public&connect_timeout=300
      - JWT_SECRET=${JWT_SECRET}
      - APP_HOST=${APP_HOST}
    networks:
      - default

volumes:
  db_data:

networks:
  default: